### PR TITLE
Catch DataWindow exceptions in PelIfd

### LINKED ISSUE #10: Exception thrown on picture
Bug created from [sourceforge](https://sourceforge.net/tracker/?func=detail&aid=1730993&group_id=108380&atid=650322)

```
require_once('PelJpeg.php'); 
$jpeg = new PelJpeg($tmpfile); 
$exif = $jpeg->getExif(); 
if ( $exif != null ) { 
    $jpeg1 = new PelJpeg($bigfile); 
    $jpeg1->setExif( $exif); 
    file_put_contents($bigfile, $jpeg1->getBytes()); 
}
```

A [test case has been created](https://github.com/lsolesen/pel/blob/master/test/bug1730993.php)

### PR DESCRIPTION
**Pull request by mondrake**
Fixes #10.

Let's face it... these test files are badly broken in terms of IFD structure. This PR just captures exceptions thrown by DataWindow and skips parts of the processing, trying to load the rest of the file one way or another, but without trying to repair anything.

### CODE REVIEW

File: src/PelIfd.php [hunk 1]
```diff
@@ -345,7 +345,12 @@ public function load(PelDataWindow $d, $offset)
 
                     if ($starting_offset != $o) {
                         $this->sub[$type] = new PelIfd($type);
-                        $this->sub[$type]->load($d, $o);
+                        try {
+                            $this->sub[$type]->load($d, $o);
+                        } catch (PelDataWindowOffsetException $e) {
+                            unset($this->sub[$type]);
```
Comment (weberhofer) [inline src/PelIfd.php]: If you "unset" the array element a hole will be kept in the array. It could be a good idea to assign the new PelIfd object to a temporary object and insert it into the array only on access instead of removing it from the array.

File: test/Bug1730993Test.php [hunk 2]
```diff
@@ -24,28 +24,19 @@
...
-            $exif = $jpeg->getExif();
-            if ($exif !== null) {
-                $jpeg1 = new PelJpeg($bigfile);
-                $jpeg1->setExif($exif);
-                file_put_contents($bigfile, $jpeg1->getBytes());
-            }
-        } catch (Exception $e) {
-            $this->fail('Test should not throw exception: ' . $e->getMessage());
-        }
+        $jpeg = new PelJpeg($tmpfile);
```
Comment (weberhofer) [inline test/Bug1730993Test.php]: Please inline the filename here, too.

File: test/Bug1730993Test.php [hunk 3]
```diff
@@ -24,28 +24,19 @@
...
+    }
+
+    function testWindowOffsetExceptionIsCaught()
+    {
+        $tmpfile = dirname(__FILE__) . '/images/27303092-d9d72838-54f6-11e7-943c-78933f9c9fbe.jpg';
```
Comment (weberhofer) [inline test/Bug1730993Test.php]: Please rename that file to match it's name with the test. Could be bug1730993-2.jpg

File: test/Bug1730993Test.php [hunk 4]
```diff
@@ -24,28 +24,19 @@
...
 use lsolesen\pel\PelJpeg;
+use PHPUnit\Framework\TestCase;
 
-class Bug1730993Test extends \PHPUnit_Framework_TestCase
+class Bug1730993Test extends TestCase
 {
-    function testThisDoesNotWorkAsExpected()
+    function testWindowWindowExceptionIsCaught()
     {
         $tmpfile = dirname(__FILE__) . '/images/bug1730993_tmp.jpg';
```
Comment (weberhofer) [inline test/Bug1730993Test.php]: Removing the "_tmp" part of the file name would be good...

File: test/Bug1730993Test.php (hunk 2 above)
Comment (weberhofer) [inline test/Bug1730993Test.php]: You can also remove the "$jpeg =" part as it's not used later on.

File: test/Bug1730993Test.php [hunk 5]
```diff
@@ -24,28 +24,19 @@
...
-        } catch (Exception $e) {
-            $this->fail('Test should not throw exception: ' . $e->getMessage());
-        }
+        $jpeg = new PelJpeg($tmpfile);
+    }
+
+    function testWindowOffsetExceptionIsCaught()
+    {
+        $tmpfile = dirname(__FILE__) . '/images/27303092-d9d72838-54f6-11e7-943c-78933f9c9fbe.jpg';
+        $jpeg = new PelJpeg($tmpfile);
```
Comment (weberhofer) [inline test/Bug1730993Test.php]: You can also remove the "$jpeg =" part as it's not used later on.

File: test/Bug1730993Test.php [hunk 6]
```diff
@@ -24,28 +24,19 @@
...
-                $jpeg1->setExif($exif);
-                file_put_contents($bigfile, $jpeg1->getBytes());
-            }
-        } catch (Exception $e) {
-            $this->fail('Test should not throw exception: ' . $e->getMessage());
-        }
+        $jpeg = new PelJpeg($tmpfile);
+    }
+
+    function testWindowOffsetExceptionIsCaught()
```
Comment (weberhofer) [inline test/Bug1730993Test.php]: @Please declare the method "public"

File: test/Bug1730993Test.php [hunk 7]
```diff
@@ -24,28 +24,19 @@
  */
 
 use lsolesen\pel\PelJpeg;
+use PHPUnit\Framework\TestCase;
 
-class Bug1730993Test extends \PHPUnit_Framework_TestCase
+class Bug1730993Test extends TestCase
 {
-    function testThisDoesNotWorkAsExpected()
+    function testWindowWindowExceptionIsCaught()
```
Comment (weberhofer) [inline test/Bug1730993Test.php]: Please declare the method "public"

**Comment by mondrake** [comment]
@weberhofer I did a bit more refactoring to tests - I hope this is ok. The idea is to have a single test class for broken images, rather than one per bug, and to name test methods in a way to meak clear which bug they cover.

**Comment by weberhofer** [comment]
Great! Thanks a lot!
